[build]
  command = "make all"  # This builds your project using the Makefile
  publish = "web"  # Adjust if your static files are in a different folder
  functions = "netlify/functions"  # For serverless functions
